# Generated by Django 4.2.6 on 2023-10-09 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_task_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profiles',
            new_name='Profile',
        ),
        migrations.RenameModel(
            old_name='ToDoLists',
            new_name='ToDoList',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
