# Generated by Django 4.2.6 on 2023-10-09 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('task', '0007_rename_profiles_profile_rename_todolists_todolist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.profile'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
